#!/bin/sh

PASS=true

if ! make doc
  then PASS = false
fi

git add readme.md

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter ACMR | grep ".go$")

if [ "$STAGED_GO_FILES" = "" ]
  then exit 0
fi

if ! gofmt -s -w $STAGED_GO_FILES
  then PASS=false
fi

if ! git add $STAGED_GO_FILES
  then PASS=false
fi

if [ "$PASS" = "false" ]
  then exit 1
fi
